In [1]:
# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.17.1
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---


In [3]:
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
import torch
from torch.utils.data import DataLoader, random_split
from a03_functions import ReviewsDataset, review_collate_fn
from a03_helper import MAX_SEQ_LEN, BATCH_SIZE, SEED


## Task 2: Data Loaders


In [6]:
# Split dataset into training, validation, and test subsets
dataset = ReviewsDataset(use_vocab=True)
train_set, val_set, test_set = random_split(
    dataset, [0.8, 0.1, 0.1], generator=torch.Generator().manual_seed(SEED)
)


### Task 2a


In [11]:
# Example usage of a data loader
dataloader = DataLoader(
    val_set,  # a dataset
    1,  # desired batch size
    False,  # whether to randomly shuffle the dataset
)


In [12]:
# Let's print the first batch
batch = next(iter(dataloader))
print(batch)

# [[tensor([11]), tensor([6]), tensor([140]), ... , tensor([8])], tensor([1])]



[[tensor([11]), tensor([6]), tensor([140]), tensor([3]), tensor([79]), tensor([16]), tensor([577]), tensor([72]), tensor([3152]), tensor([87]), tensor([8]), tensor([317]), tensor([82]), tensor([3]), tensor([388]), tensor([47]), tensor([3569]), tensor([18]), tensor([37]), tensor([188]), tensor([200]), tensor([1185]), tensor([48]), tensor([14]), tensor([332]), tensor([17]), tensor([42]), tensor([18]), tensor([5140]), tensor([2965]), tensor([5]), tensor([205]), tensor([45]), tensor([9]), tensor([1]), tensor([28555]), tensor([539]), tensor([2]), tensor([357]), tensor([42]), tensor([66]), tensor([6]), tensor([35]), tensor([3417]), tensor([5]), tensor([154]), tensor([36]), tensor([2318]), tensor([38]), tensor([11]), tensor([3626]), tensor([10]), tensor([26]), tensor([3]), tensor([166]), tensor([4]), tensor([1200]), tensor([18]), tensor([42]), tensor([15]), tensor([3]), tensor([388]), tensor([1]), tensor([62]), tensor([152]), tensor([10]), tensor([89]), tensor([21]), tensor([39]), tensor([6])

### Task 2b


In [15]:
# Test your function
review_collate_fn([([1, 2, 3], 1), (torch.arange(MAX_SEQ_LEN * 2) + 1, 0)])

# Should yield:
# (tensor([[  1,   2,   3,   0,   0,  ..., 0 ],
#          [  1,   2,   3,   4,   5, ..., 200 ]]),
#  tensor([1, 0]))


(tensor([[  1,   2,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0, 

In [16]:
# Create the data loaders (with shuffling for training data -> randomization)
train_loader = DataLoader(train_set, BATCH_SIZE, True, collate_fn=review_collate_fn)
val_loader = DataLoader(val_set, BATCH_SIZE, False, collate_fn=review_collate_fn)
test_loader = DataLoader(test_set, BATCH_SIZE, False, collate_fn=review_collate_fn)


In [17]:
# Let's print the first batch
batch = next(iter(val_loader))
print(batch)

# (
#   tensor([[  11,    6,  140,  ...,    0,    0,    0],
#         [  10,  123,  345,  ...,    0,    0,    0],
#         [   1,  822,  331,  ...,    0,    0,    0],
#         ...,
#         [   3,   50,  798,  ...,    0,    0,    0],
#         [ 417,   96,   35,  ...,    0,    0,    0],
#         [  25,   23,    3,  ..., 7774,  110,   73]]),
#   tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
#         1, 0, 0, 0, 0, 0, 1, 1])
# )


(tensor([[  11,    6,  140,  ...,    0,    0,    0],
        [  10,  123,  345,  ...,    0,    0,    0],
        [   1,  822,  331,  ...,    0,    0,    0],
        ...,
        [   3,   50,  798,  ...,    0,    0,    0],
        [ 417,   96,   35,  ...,    0,    0,    0],
        [  25,   23,    3,  ..., 7774,  110,   73]]), tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 1, 1]))
