In [1]:
# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.17.1
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---


In [3]:
%load_ext autoreload
%autoreload 2

import torch
from a03_functions import SimpleLSTM
from a03_helper import DEVICE



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Task 3: Recurrent Neural Networks


In [9]:
# Test constructor
model = SimpleLSTM(50, 10, 32, 2, 0.1).to(DEVICE)
print(model)

# Should give:
# SimpleLSTM(
#   (embedding): Embedding(50, 10)
#   (lstm): LSTM(10, 32, num_layers=2, batch_first=True, dropout=0.1)
#   (fc): Linear(in_features=32, out_features=1, bias=True)
#   (sigmoid): Sigmoid()
# )


SimpleLSTM(
  (embedding): Embedding(50, 10)
  (lstm): LSTM(10, 32, num_layers=2, batch_first=True, dropout=0.1)
  (fc): Linear(in_features=32, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [10]:
# Test forward pass (with a batch of 3 examples)
model = SimpleLSTM(50, 10, 32, 2).to(DEVICE)
dummy_data = torch.arange(30, dtype=torch.int, device=DEVICE).reshape(3, 10)

# Test with fixed model parameters
for key in model.state_dict():
    model.state_dict()[key][:] = 0.1
probs, states = model(dummy_data)
print(probs)
print(states)


# tensor([[0.9643],
#         [0.9643],
#         [0.9643]], device='cuda:0 or cpu', grad_fn=<SigmoidBackward0>)
# tensor([[0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985],
#         [0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985],
#         [0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985]], device='cuda:0 or cpu',
#        grad_fn=<SliceBackward0>)


tensor([[0.9643],
        [0.9643],
        [0.9643]], grad_fn=<SigmoidBackward0>)
tensor([[0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985],
        [0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985],
        [0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985]], grad_fn=<SelectBackward0>)


In [14]:
# Test with random model parameters
for key in model.state_dict():
    A = model.state_dict()[key]
    A[:] = torch.randn(*A.shape)
probs, states = model(dummy_data)
print(probs)
print(states)
# You should now see different outputs for each of the three examples. Run this multiple
# times; you should see output probabilities in the entire range from [0-1] (i.e., not
# just extremes)


tensor([[0.9395],
        [0.9957],
        [0.3157]], grad_fn=<SigmoidBackward0>)
tensor([[-1.1420e-02,  5.1626e-02, -3.1701e-01,  1.1664e-01, -4.8955e-01,
          5.6336e-02, -1.4837e-04, -9.2949e-01,  9.5114e-01,  8.2746e-01,
          3.6455e-03,  1.0780e-02, -3.0867e-01, -3.2691e-02,  1.6498e-01,
          5.1271e-01,  7.2827e-01,  1.1947e-02,  3.6393e-02,  4.2286e-04,
          6.6756e-02, -7.1546e-01,  1.4717e-01,  8.4807e-03,  2.4344e-01,
          3.1455e-01, -4.2743e-01, -3.6902e-02, -5.9888e-05, -9.9594e-04,
         -6.6463e-01, -4.5064e-01],
        [-2.1650e-03,  8.9338e-01, -6.3746e-01,  1.1135e-01, -5.7276e-04,
         -5.3600e-01, -2.0838e-02,  2.5408e-02, -7.1934e-02, -5.4170e-01,
          4.8720e-01, -2.3183e-01, -9.6821e-02,  5.0007e-03, -6.0358e-03,
          1.6298e-02,  7.0277e-01,  4.5773e-02,  4.8429e-03, -2.0716e-03,
          1.9255e-02, -6.8902e-01,  5.1248e-01, -1.6970e-03,  5.9268e-01,
          5.6684e-01, -2.2549e-01,  2.2356e-02,  6.9967e-05, -3.204