In [10]:
# ---
# jupyter:
#   jupytext:
#     formats: py:percent,ipynb
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.16.7
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---


# Task 1: Implement an MLP
## 1a Logistic Regression
#
The class `LogisticRegression` is located in `a01_functions.py`. You can make
experimental changes to that class in the other file (`a01_functions.py`). All
saved changes will be automatically reflected here due to the IPython
autoreload extension (see below).



In [11]:
import torch


%load_ext IPython.extensions.autoreload
%autoreload 2
from a01_functions import LogisticRegression, MLP


The IPython.extensions.autoreload extension is already loaded. To reload it, use:
  %reload_ext IPython.extensions.autoreload


In [12]:
# let's test it
logreg = LogisticRegression(3, 2)
x = torch.rand(3)  # input
logreg(x)  # output (log probabilities)
logreg(x).exp()  # output (probabilities)


tensor([0.5712, 0.4288])

In [13]:
# you can access individual parameters as follows
logreg.get_parameter("0_bias")


Parameter containing:
tensor([ 0.2037, -0.0053], requires_grad=True)

In [14]:
# or all of them at once
list(logreg.named_parameters())


[('0_weight',
  Parameter containing:
  tensor([[ 0.1495, -0.5945],
          [-0.2891,  0.1578],
          [-0.5301, -0.0233]], requires_grad=True)),
 ('0_bias',
  Parameter containing:
  tensor([ 0.2037, -0.0053], requires_grad=True))]

In [15]:
# or directly the tensors stored in the parameters
for par, value in logreg.state_dict().items():
    print(f"{par:<15}= {value}")



0_weight       = tensor([[ 0.1495, -0.5945],
        [-0.2891,  0.1578],
        [-0.5301, -0.0233]])
0_bias         = tensor([ 0.2037, -0.0053])


## 1b MLP
#
The class `MLP` is also located in `a01_functions.py`. The implementation must
also be in that file (`a01_functions.py`) as it will be used in later tasks.
#
Once your implementation is complete, you can proceed with the cells below.


In [16]:
# here you should see the correct parameter sizes
mlp = MLP([2, 3, 4, 2], torch.relu)
list(mlp.named_parameters())


[('0_weight',
  Parameter containing:
  tensor([[-0.6466,  0.8188,  0.1183],
          [-1.1154,  0.7558, -0.3581]], requires_grad=True)),
 ('0_bias',
  Parameter containing:
  tensor([-0.8407,  1.3236, -0.0561], requires_grad=True)),
 ('1_weight',
  Parameter containing:
  tensor([[ 0.6722, -0.4000, -0.5699,  0.5806],
          [-0.2545, -0.2606,  0.4053, -0.1354],
          [ 0.6355, -0.5074,  0.8752,  0.2938]], requires_grad=True)),
 ('1_bias',
  Parameter containing:
  tensor([ 0.5455, -0.7030, -0.6188, -0.3862], requires_grad=True)),
 ('2_weight',
  Parameter containing:
  tensor([[-0.6003, -0.1677],
          [-0.0572, -0.2269],
          [ 1.1528, -0.1895],
          [-0.2335, -0.2304]], requires_grad=True)),
 ('2_bias',
  Parameter containing:
  tensor([0.8946, 1.1134], requires_grad=True))]

In [24]:
# Test your code; we fix the parameters and check the result
with torch.no_grad():
    torch.manual_seed(0)
    for l in range(mlp.num_layers()):
        W, b = mlp.get_parameter(f"{l}_weight"), mlp.get_parameter(f"{l}_bias")
        W[:] = torch.randn(W.shape)
        b[:] = torch.randn(b.shape)

mlp(torch.tensor([-1.0, 2.0]))  # must give: [ 0.8315, -3.6792]


tensor([ 0.8315, -3.6792], grad_fn=<AddBackward0>)

In [27]:
# You can also evaluate your model on multiple inputs at once. Here "torch.func.vmap"
# produces a function that applies the provided function (mlp#forward) to each row of
# its argument (torch.tensor...).
#
# [[ 0.8315, -3.6792],
# [ 4.8448, -6.8813]]
torch.func.vmap(mlp)(torch.tensor([[-1.0, 2.0], [1.0, -2.0]]))


tensor([[ 0.8315, -3.6792],
        [ 4.8448, -6.8813]], grad_fn=<AddBackward0>)

## 1c Batching


In [28]:
# After you adapted the MLP class, you should get the same results as above.
mlp(torch.tensor([-1.0, 2.0]))  # must give: [ 0.8315, -3.6792]


tensor([ 0.8315, -3.6792], grad_fn=<AddBackward0>)

In [30]:
# Now without vmap. Only proceed to task 2 once this works correctly.
#
# [[ 0.8315, -3.6792],
# [ 4.8448, -6.8813]]
mlp(torch.tensor([[-1.0, 2.0], [1.0, -2.0]]))


tensor([[ 0.8315, -3.6792],
        [ 4.8448, -6.8813]], grad_fn=<AddBackward0>)